name: ETF Genetic Optimization
on:
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install pandas numpy pandas_market_calendars huggingface_hub pyarrow fastparquet scipy
      - name: Execute Engine
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python train.py
